Add test infrastructure

diff --git a/test/Makefile b/test/Makefile
--- a/test/Makefile
+++ b/test/Makefile
@@ -1,24 +1,77 @@
 #
-# This makefile orchestrates the staging environment.
-#
-# Usage:
-#
-# - make          by default, make will pull the latest commit from the registry and run the container detached
-# - make build    build the staging image
-# - make stop     stop the container
-# - make remove   stop the container and delete the image
-# - make run      set up a staging container for working with diffs in real-time
-#
-# Submake usage:
-#
-# These will execute the Makefile in the corresponding subdirectory. Execute a specific
-# target by using the "TARGET" flag.
-#
-# - make docker [TARGET=target]
+# This Makefile runs all xapprentice tests for Vim and Neovim, and can configure a staging
+# environment.
 #
 
-.PHONY: stop remove run docker vim nvim
+# Tests ...
+########################################################################
 
+# Use Vim or Neovim.
+VIMPROG := vim
+NVIMPROG := nvim
+
+.PHONY: default $(VIMPROG) $(NVIMPROG) log clean cleanall report test
+
+default: $(VIMPROG)
+
+# Test files should be appended to the TESTS variable in this file.
+include Make_all.mak
+
+$(VIMPROG): PROG := $(VIMPROG)
+$(VIMPROG): RUN_PROG_TEST := $(PROG) -Nu setup.vim $(NO_INITS)
+$(VIMPROG): clean test log report
+
+$(NVIMPROG): PROG := $(NVIMPROG)
+$(NVIMPROG): RUN_PROG_TEST := $(PROG) -Nu setup.vim $(NO_INITS) --headless 2>/dev/null
+$(NVIMPROG): clean test log report
+
+log:
+	@/bin/sh -c 'if grep --quiet --no-messages "FAILED" messages; then \
+					if ! test -d ./logs; then mkdir -- logs; fi; \
+					cp messages logs/xapprentice-$(PROG)-`date --iso-8601=seconds`.log; \
+				fi'
+
+clean:
+	-rm -f --verbose *.res messages
+
+cleanall: clean
+	-rm -rf --verbose logs
+
+# Limitation: these tests only work if Vim/Neovim has been compiled with the +eval
+# feature. To check run the following in Vim/Neovim:
+#
+#     :echo has('eval')
+#
+# If a 1 (true) was echoed then Vim/Neovim has been compiled with the +eval feature.
+report:
+	@/bin/sh -c 'if test -f messages; then cat messages; \
+					echo -en "\\nTest results: "; \
+					if grep --quiet --no-messages "FAILED" messages; then echo "FAILED"; exit 1; \
+					else echo "SUCCESS"; fi; \
+				fi'
+
+test: $(TESTS)
+
+# This is a pattern rule that defines an implicit rule to make .res files from .vim
+# files. To create new tests create a file "*.vim", e.g. test_file1.vim and place it in
+# the same directory as this Makefile. Then add the test file name to the TESTS variable
+# in the Make_all.mak file, replacing the .vim file extension with .res, like so:
+#
+#     TESTS = test_file1.res test_file2.res
+#
+# After `make` is run, two files: test_file1.res and test_file2.res will be in created in
+# the same directory as this Makefile.
+%.res :: %.vim
+	@echo "$(PROG)" > vimcmd
+	@echo "$(RUN_PROG_TEST)" >> vimcmd
+	$(RUN_PROG_TEST) -S runtests.vim $<
+	@rm vimcmd
+
+
+
+# Staging ...
+########################################################################
+.PHONY: stop rm run docker
 
 # If the "user" has been added to the "docker" group then this can be changed to
 # "docker := docker". Alternatively, run make with the "-e" flag, like so:
@@ -41,23 +94,15 @@ ifeq ($(shell ${docker} inspect --format "{{.State.Running}}" ${name} 2>/dev/nul
 	@${docker} rm -f ${name}
 endif
 
-remove: stop
+rm: stop
 	$(info Deleting ${stage} ...)
-	@${docker} image rm ${stage}
+	@${docker} image rm -f ${stage}
 
 run: stop
 	$(info Running ${stage} ...)
 	@${docker} run -d -t \
-		--volume $(shell pwd):/root/.vim \
+		--volume $(shell pwd)/..:/root/.vim \
 		--hostname alpine \
 		--name ${name} \
 		${stage}
 	@${docker} exec -t vim_xapprentice_stage /bin/bash './.vim/test/files/linker.sh'
-
-
-
-# Submake ...
-########################################################################
-docker:
-	$(info Running tests in local environment ...)
-	@$(MAKE) --directory=$@ $(TARGET)
